### ISSUE TITLE
configurable .git directory?

### ISSUE THREAD

**Issue by einsweniger** [SIMULATAN/gradle-buildinfo-plugin#2]
hi, thank you for making this, it's really helping us.

unfortunately, we've got the edge case, that our `.git` dir is not found under the folder you're assuming in https://github.com/SIMULATAN/gradle-buildinfo-plugin/blob/2374318d944b08d7fa487b0e88ca227e9b859213/src/main/kotlin/io/github/simulatan/gradle/plugin/buildinfo/configuration/BuildInfoExtension.kt#L47

and since it's a `val` instead of  `var` so we can't change that. could you make this configurable? That would be awesome!

Thank you!

**Comment by SIMULATAN** [comment]
Hi, great to hear my work is helping someone!
I'm surprised about this oversight, since I thought I used the option in a project of mine myself..
In any case, I just fixed the problem and published [2.3.1](https://plugins.gradle.org/plugin/io.github.simulatan.gradle-buildinfo-plugin/2.3.1). Kindly let me know if any other issues come up!

**Comment by einsweniger** [comment]
thank you for responding so quickly! unfortunately, I just found out, that I cannot use the extension because it's not compatible with the gradle configuration-cache 😅 As I understand, being compatible with that cache is not trivial, so I'm not sure if you'd would want to spend the time doing that

**Comment by SIMULATAN** [comment]
Hm, interesting... the Plugin is rather small, so *surely* it can't be *that* hard, right :^)
If you want to, please open a separate issue and link your findings and I'll take a look at it asap.

**Comment by einsweniger** [comment]
you might be able to use this as blueprint: https://github.com/hndrs/gradle-git-properties-plugin 
have not looked at their code, tho.
